title: Qitong Chen
description: Ph.D. student candidate in Computer Science and Technology at Soochow University.
author: Qitong Chen
avatar: /qtchen2.jpg
email: qtchen0730@163.com
location: SuZhou, China
url: https://qtchen730.github.io/qtchen.github.io
github: https://github.com/qtchen730
skin: sunrise  # midnight daylight sunrise sunset
subscribe: true
orcid: https://orcid.org/my-orcid?orcid=0000-0001-8970-1345

 
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Qitong Chen
  links:
    - https://twitter.com/ngzhio
    - https://www.facebook.com/ngzhio
    - https://github.com/qtchen730
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
